### ISSUE TITLE
dump() bug at city hall

### ISSUE THREAD

**Issue by tevpg** [ironwoodcall/TagTracker#170]
```
 14:52  Bike tag or command >>> bk5
  Bike bk5 checked IN                      <---in---  
  
  14:55  Bike tag or command >>> dump
  
    cfg   
Traceback (most recent call last):
  File "/home/bikevalet/TagTracker/tagtracker.py", line 1044, in <module>
    main()
  File "/home/bikevalet/TagTracker/tagtracker.py", line 821, in main
    dump_data()
  File "/home/bikevalet/TagTracker/tagtracker.py", line 746, in dump_data
    if isinstance(value, Union[str, dict, list, set, float, int]):
  File "/usr/lib/python3.9/typing.py", line 703, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/usr/lib/python3.9/typing.py", line 706, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks

**Comment by tevpg** [comment]
This seems to be a python version problem. The problem is the call to isinstance with a Union of types.

**Comment by tevpg** [comment]
a simple tuple instead of a Union as arg to isinstance() matches the 3.9 documentation, let's try that.
