### ISSUE TITLE
Crash on seemingly normal return-out

### ISSUE THREAD

**Issue by ironwoodcall** [ironwoodcall/TagTracker#242]
```
  11:38  Bike tag or command >>> wb13
  Bike wb13 checked out at 11:42                          ---out--->  
Traceback (most recent call last):
  File "/home/bikevalet/TagTracker/tagtracker.py", line 1133, in <module>
    main()
  File "/home/bikevalet/TagTracker/tagtracker.py", line 972, in main
    pr.echo_flush()
  File "/home/bikevalet/TagTracker/tt_printer.py", line 104, in echo_flush
    _echo_file.flush()
OSError: [Errno 107] Transport endpoint is not connected

TagTracker done.

Restart TagTracker? (Y/N): y

Starting TagTracker...
```

The return-out was successfully recorded before crashing:

```
 11:43  Bike tag or command >>> ?wb13
  
   8:46  wb13 checked in
  11:42  wb13 checked out
```

**Comment by tevpg** [comment]
tracked in #245
