### ISSUE TITLE
crashes for some tags

### ISSUE THREAD

**Issue by tevpg** [ironwoodcall/TagTracker#60]
Found during meeting with JP
```
Bike tag or command >>> bi4
Traceback (most recent call last):
  File "C:\Users\todd\Documents\wk\capital_bike\TagTracker\tagtracker.py", line 1007, in <module>
    main()
  File "C:\Users\todd\Documents\wk\capital_bike\TagTracker\tagtracker.py", line 962, in main
    tag_check(cmd)
  File "C:\Users\todd\Documents\wk\capital_bike\TagTracker\tagtracker.py", line 864, in tag_check
    query_tag(tag)
  File "C:\Users\todd\Documents\wk\capital_bike\TagTracker\tagtracker.py", line 454, in query_tag
    target = (args + [None])[0]
TypeError: can only concatenate str (not "list") to str

C:\Users\todd\Documents\wk\capital_bike\TagTracker>python tagtracker.py
TagTracker 0.7.2 by Julias Hocking
Previous log for today successfully loaded

Bike tag or command >>> ba1
  Unrecognized tag or command.
  Enter 'h' for help.

Bike tag or command >>> pa1
  pa1 checked IN

Bike tag or command >>> be0
Traceback (most recent call last):
  File "C:\Users\todd\Documents\wk\capital_bike\TagTracker\tagtracker.py", line 1007, in <module>
    main()
  File "C:\Users\todd\Documents\wk\capital_bike\TagTracker\tagtracker.py", line 962, in main
    tag_check(cmd)
  File "C:\Users\todd\Documents\wk\capital_bike\TagTracker\tagtracker.py", line 864, in tag_check
    query_tag(tag)
  File "C:\Users\todd\Documents\wk\capital_bike\TagTracker\tagtracker.py", line 454, in query_tag
    target = (args + [None])[0]
TypeError: can only concatenate str (not "list") to str

```
[cityhall_2023-05-11.log](https://github.com/ironwoodcall/TagTracker/files/11456043/cityhall_2023-05-11.log)

**Comment by tevpg** [comment]
Problem was that when I changed the header for query_tag() I didn't realize it was called by edit_tag().

Addressed in branch feat/59/colours(1)
